# Generated by Django 3.2.4 on 2021-06-17 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='[Sem titulo]', max_length=90)),
                ('bio', models.TextField(max_length=1000)),
                ('data_create', models.DateField(default=datetime.datetime(2021, 6, 17, 0, 52, 4, 464878, tzinfo=utc))),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author')),
            ],
        ),
    ]
