# Generated by Django 3.2.4 on 2021-06-17 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20210617_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='data_create',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 17, 16, 813508, tzinfo=utc)),
        ),
    ]
