# Generated by Django 3.2.4 on 2021-06-18 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20210617_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_create',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
