# Generated by Django 3.2.4 on 2021-06-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20210619_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
