# Generated by Django 3.2.4 on 2021-06-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_publication_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='comentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.comentario'),
        ),
    ]
