# Generated by Django 3.2.4 on 2021-06-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='bio',
            field=models.TextField(max_length=15000),
        ),
    ]
