# Generated by Django 3.2.4 on 2021-06-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='prfile_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
