# Generated by Django 3.2.4 on 2021-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_prfile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='curriculo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
