# Generated by Django 3.2.4 on 2021-06-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20210620_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
