# Generated by Django 3.2.4 on 2021-06-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20210620_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='localization',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
